version: '3'
services:
  db:
    image: postgres:12.2
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - fullstack
  go-example:
    depends_on:
      - db
    image: strongjz/golang_example:0.0.6
    ports:
      - "${PORT}:${PORT}"
      - "${AD_PORT}:${AD_PORT}"
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      AD_PORT: ${AD_PORT}
      VERSION: ${VERSION}
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge